---
abstract: 'Data centric form(s) toolkit'
author:
  - 'Jerome Eteve <jerome.eteve@gmail.com>'
build_requires:
  DBD::SQLite: 0
  DBI: 0
  DBIx::Class::Schema::Loader: 0
  Data::Dumper: 0
  MyFormBase: 0
  Test::Exception: 0
  Test::More: 0
  base: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Form-Toolkit
requires:
  Class::Load: 0
  DateTime: 0
  DateTime::Format::ISO8601: 0
  JSON: 0
  MIME::Base64: 0
  Mail::RFC822::Address: 0
  Module::Pluggable::Object: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util: 0
  MooseX::Clone: 0
  Scalar::Util: 0
  perl: 5.010_000
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/jeteve/Form-Toolkit/issues
  homepage: https://github.com/jeteve/Form-Toolkit
  repository: https://github.com/jeteve/Form-Toolkit.git
version: 0.004
